// <auto-generated />
namespace DALEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddViewChangea1qswasdssw : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddViewChangea1qswasdssw));
        
        string IMigrationMetadata.Id
        {
            get { return "201706011542215_AddViewChangea1qswasdssw"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
