//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of Customer.
        /// </summary>
        internal static string CustomerIdNotSet {
            get {
                return ResourceManager.GetString("CustomerIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer not found.
        /// </summary>
        internal static string CustomerNotFound {
            get {
                return ResourceManager.GetString("CustomerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is null reference.
        /// </summary>
        internal static string CustomerNullReference {
            get {
                return ResourceManager.GetString("CustomerNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of Format.
        /// </summary>
        internal static string FormatIdNotSet {
            get {
                return ResourceManager.GetString("FormatIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format not found.
        /// </summary>
        internal static string FormatNotFound {
            get {
                return ResourceManager.GetString("FormatNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[A-Za-z0-9_]{3,16}$.
        /// </summary>
        internal static string loginPattern {
            get {
                return ResourceManager.GetString("loginPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login must be at least 3 characters and no more than 16 characters. Can contain any letter, number, underscore and hyphen..
        /// </summary>
        internal static string LoginValidateMessage {
            get {
                return ResourceManager.GetString("LoginValidateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Money Precision value must be greater or equal to 0 and less than or equal to 8.
        /// </summary>
        internal static string MoneyPrecisionValidate {
            get {
                return ResourceManager.GetString("MoneyPrecisionValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&amp;*_-])[\S].{8,}$.
        /// </summary>
        internal static string passwordPattern {
            get {
                return ResourceManager.GetString("passwordPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 characters and contain uppercase letters, lowercase letters, numbers, special characters..
        /// </summary>
        internal static string PasswordValidateMessage {
            get {
                return ResourceManager.GetString("PasswordValidateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Percenty Precision value must be greater or equal to 0 and less than or equal to 8.
        /// </summary>
        internal static string PercentyPrecisionValidate {
            get {
                return ResourceManager.GetString("PercentyPrecisionValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of Portfolio.
        /// </summary>
        internal static string PortfolioIdNotSet {
            get {
                return ResourceManager.GetString("PortfolioIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio not found.
        /// </summary>
        internal static string PortfolioNotFound {
            get {
                return ResourceManager.GetString("PortfolioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio is null reference.
        /// </summary>
        internal static string PortfolioNullReference {
            get {
                return ResourceManager.GetString("PortfolioNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent Wins of portfolio cannot be less than zero.
        /// </summary>
        internal static string PortfolioPercentWinsValidate {
            get {
                return ResourceManager.GetString("PortfolioPercentWinsValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of Position.
        /// </summary>
        internal static string PositionIdNotSet {
            get {
                return ResourceManager.GetString("PositionIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position not found.
        /// </summary>
        internal static string PositionNotFound {
            get {
                return ResourceManager.GetString("PositionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is null reference.
        /// </summary>
        internal static string PositionNullReference {
            get {
                return ResourceManager.GetString("PositionNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Weight value must be greater than 0 and less than or equal to 10,000..
        /// </summary>
        internal static string PositionOpenWeightValidate {
            get {
                return ResourceManager.GetString("PositionOpenWeightValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of Profile.
        /// </summary>
        internal static string ProfileIdNotSet {
            get {
                return ResourceManager.GetString("ProfileIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found.
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile is null reference.
        /// </summary>
        internal static string ProfileNullReference {
            get {
                return ResourceManager.GetString("ProfileNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with such login already exist.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of User.
        /// </summary>
        internal static string UserIdNotSet {
            get {
                return ResourceManager.GetString("UserIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of view.
        /// </summary>
        internal static string ViewIdNotSet {
            get {
                return ResourceManager.GetString("ViewIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View not found.
        /// </summary>
        internal static string ViewNotFound {
            get {
                return ResourceManager.GetString("ViewNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View is null reference.
        /// </summary>
        internal static string ViewNullReference {
            get {
                return ResourceManager.GetString("ViewNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of ViewTemplateColumn.
        /// </summary>
        internal static string ViewTemplateColumnIdNotSet {
            get {
                return ResourceManager.GetString("ViewTemplateColumnIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set Name of ViewTemplateColumn.
        /// </summary>
        internal static string ViewTemplateColumnNameNotSet {
            get {
                return ResourceManager.GetString("ViewTemplateColumnNameNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewTemplateColumn not found.
        /// </summary>
        internal static string ViewTemplateColumnNotFound {
            get {
                return ResourceManager.GetString("ViewTemplateColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewTemplateColumn is null reference.
        /// </summary>
        internal static string ViewTemplateColumnNullReference {
            get {
                return ResourceManager.GetString("ViewTemplateColumnNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not set id of ViewTemplate.
        /// </summary>
        internal static string ViewTemplateIdNotSet {
            get {
                return ResourceManager.GetString("ViewTemplateIdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewTemplate not found.
        /// </summary>
        internal static string ViewTemplateNotFound {
            get {
                return ResourceManager.GetString("ViewTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewTemplate is null reference.
        /// </summary>
        internal static string ViewTemplateNullReference {
            get {
                return ResourceManager.GetString("ViewTemplateNullReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong login or password.
        /// </summary>
        internal static string WrongLogOrPass {
            get {
                return ResourceManager.GetString("WrongLogOrPass", resourceCulture);
            }
        }
    }
}
